[package]
name = "papyri"
version = "0.3.1"
edition = "2021"
license = "MIT"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[features]
default = ["syntect"]

[dependencies]
arg = "0.3.1"
aho-corasick = "0.7.19"
glob = "0.3.0"
htmlentity = "1.2.0"
indexmap = "1.9.1"
maplit = "1.0.2"
once_cell = "1.16.0"
regex = "1.7.0"
regex-lexer = "0.2.0"
syntect = {version = "5.0.0", optional = true, features = ["parsing"]}
