---
name: Create release from tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build executable
        run: cargo build --release
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Name executable (Linux/MacOS)
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          mv target/release/papyri papyri-${{ steps.tagName.outputs.tag }}-${{ matrix.os }}
      - name: Name executable (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: |
          mv target/release/papyri papyri-${{ steps.tagName.outputs.tag }}-${{ matrix.os }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: papyri-${{ matrix.os }}
          path: papyri-*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Make artifacts folder
        run: mkdir artifacts
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Flatten artifacts directory # From https://unix.stackexchange.com/a/52816
        run: find . -mindepth 2 -type f -exec mv -t . -i '{}' +
      - name: Release 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*
